version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - .:/app
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "3000:3000"
    links:
      - db   