# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e3782fbe6c2d2b4dcb29ad55565996e42148fda4288a8fa10b48fae53435496737b8b3a7bd63bc393bdab8ac808d9ad4edd77e18ef39c31664a43d1303cfc4

test:
  secret_key_base: 34d0c665d81fc8fb767b246c59c6082a714be45343d2cd900d1dc73f3d0eb8a15a5f982f5b9c833069a1d6aedac4dcd3148111df71375effb4473d553c6bf334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
